name: lethe
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_3
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.6.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.48.2
      - brotli==1.2.0
      - certifi==2025.11.12
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - clip==1.0
      - colorama==0.4.6
      - cpm-kernels==1.0.11
      - dataproperty==1.1.0
      - datasets==4.4.1
      - dill==0.4.0
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - evaluate==0.4.0
      - exceptiongroup==1.3.1
      - fairscale==0.4.13
      - fastapi==0.121.3
      - ffmpy==1.0.0
      - filelock==3.19.1
      - fire==0.7.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio-client==2.0.0.dev3
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - icetk==0.0.4
      - idna==3.11
      - immutables==0.21
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - mergekit==0.1.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.3
      - ninja==1.13.0
      - nltk==3.9.2
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - open-clip-torch==2.32.0
      - openai==2.9.0
      - opencv-python==4.12.0.88
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - pathlib==1.0.1
      - pathtools==0.1.2
      - pathvalidate==3.3.1
      - peft==0.18.0
      - pillow==11.3.0
      - portalocker==3.2.0
      - propcache==0.4.1
      - protobuf==3.20.3
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pycountry==22.3.5
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pytablewriter==1.0.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - responses==0.18.0
      - rich==14.2.0
      - rouge-score==0.1.2
      - rwkv==0.7.3
      - sacrebleu==2.3.1
      - safehttpx==0.1.7
      - safetensors==0.5.3
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.45.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.50.0
      - sympy==1.14.0
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tiktoken==0.3.3
      - timm==0.3.2
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.3.1+cu121
      - torchaudio==2.3.1+cu121
      - torchvision==0.18.1+cu121
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==2.3.1
      - typepy==1.3.4
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - xxhash==3.6.0
      - yarl==1.22.0
